name = "GitHubTest17"
uuid = "69f6048e-dadd-4262-8118-fbfe9edfb646"
repo = "https://github.com/amruthbalbail/registry-17"

[packages]
587475ba-b771-5e3f-ad9e-33799f191a9c = { name = "Flux", path = "F/Flux" }
c3e4b0f8-55cb-11ea-2926-15256bba5781 = { name = "Pluto", path = "P/Pluto" }
